[ 2023-05-15 21:41:47,135 ] 22 root - INFO: PREDICTION PIPELINE INITIATED
[ 2023-05-15 21:41:47,781 ] 26 root - INFO: INPUT OBTAINED AS [{'Delivery_person_ID': 'DEHRES17DEL01', ' Delivery_person_Age': 34, ' Delivery_person_Ratings': 3.5, ' Restaurant_latitude': 30.327968, ' Restaurant_longitude': 78.046106, ' Delivery_location_latitude': 30.397968, ' Delivery_location_longitude': 78.116106, ' Order_Date': '5-15-2023', ' Time_Orderd': datetime.time(7, 11), ' Time_Order_picked': datetime.time(7, 50), ' Weather_conditions': 'Stormy', ' Road_traffic_density': 'Medium', ' Vehicle_condition': 0, ' Type_of_order': 'Meal', ' Type_of_vehicle': 'scooter', ' multiple_deliveries': 1.0, ' Festival': 'Yes', ' City': 'Metropolitan'}]
[ 2023-05-15 21:41:47,782 ] 19 root - INFO: Input values ingestion INITIATED
[ 2023-05-15 21:41:47,783 ] 45 root - CRITICAL: Exception logged from file [c:\users\u1143589\learning\ineuron\ml\food_delivery_time\src\components\prediction.py] line no. [22] with message [If using all scalar values, you must pass an index]
