[ 2023-05-16 00:59:19,439 ] 22 root - INFO: PREDICTION PIPELINE INITIATED
[ 2023-05-16 00:59:19,445 ] 26 root - INFO: INPUT OBTAINED AS [{'ID': 0, 'Delivery_person_ID': 'JAPRES06DEL01', 'Delivery_person_Age': 34, 'Delivery_person_Ratings': 3.5, 'Restaurant_latitude': 26.911927, 'Restaurant_longitude': 75.797282, 'Delivery_location_latitude': 26.951927, 'Delivery_location_longitude': 75.837282, 'Order_Date': '02-04-2022', 'Time_Orderd': '19:20', 'Time_Order_picked': '19:25', 'Weather_conditions': 'Stormy', 'Road_traffic_density': 'Medium', 'Vehicle_condition': 0, 'Type_of_order': 'Meal', 'Type_of_vehicle': 'scooter', 'multiple_deliveries': 1.0, 'Festival': 'Yes', 'City': 'Metropolitan'}]
[ 2023-05-16 00:59:19,446 ] 19 root - INFO: Input values ingestion INITIATED
[ 2023-05-16 00:59:19,447 ] 23 root - INFO: input dictionary loaded as a dataframe
[ 2023-05-16 00:59:19,447 ] 26 root - INFO: CALLING utils for cleaning in Predictor.ingest at prediction.py
[ 2023-05-16 00:59:19,447 ] 29 root - INFO: df RECEIVED for cleaning in clean() at data_preparation_utils.py, shape: (1, 19)
[ 2023-05-16 00:59:19,448 ] 31 root - INFO: ID column dropped
[ 2023-05-16 00:59:19,449 ] 39 root - INFO: Records with faulty time dropped
[ 2023-05-16 00:59:19,464 ] 41 root - INFO: df cleaning COMPLETE in clean() at data_preparation_utils.py, shape: (1, 18), and returned
        Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  ...  multiple_deliveries  Festival          City
values      JAPRES06DEL01                   34                      3.5  ...                  1.0       Yes  Metropolitan

[1 rows x 18 columns]
[ 2023-05-16 00:59:19,477 ] 28 root - INFO: RECEIVED 
       Delivery_person_ID  Delivery_person_Age  Delivery_person_Ratings  ...  multiple_deliveries  Festival          City
values      JAPRES06DEL01                   34                      3.5  ...                  1.0       Yes  Metropolitan

[1 rows x 18 columns]
[ 2023-05-16 00:59:19,477 ] 29 root - INFO: RECEIVED input dataframe cleaned, with shape (1, 18)
[ 2023-05-16 00:59:19,477 ] 32 root - INFO: CALLING utils for feature engineering in Predictor.ingest at prediction.py, shape (1, 18)
[ 2023-05-16 00:59:19,477 ] 89 root - INFO: df received for Feature engineering, shape: (1, 18) in apply_feature_engineering() at data_preparation_utils.py
[ 2023-05-16 00:59:19,478 ] 92 root - INFO: Time_Orderd and Time_Order_picked columns converted to hours
[ 2023-05-16 00:59:19,480 ] 97 root - INFO: Order_Date split to Order_Day and Order_Month
[ 2023-05-16 00:59:19,481 ] 103 root - INFO: Geo_Distance column added
[ 2023-05-16 00:59:19,482 ] 105 root - INFO: df feature engineering steps complete in apply_feature_engineering() at data_preparation_utils.py, shape: (1, 20), and returned
[ 2023-05-16 00:59:19,482 ] 34 root - INFO: RECEIVED input dataframe feature engineered
[ 2023-05-16 00:59:19,482 ] 37 root - INFO: CALLING utils for transformation in Predictor.ingest at prediction.py
[ 2023-05-16 00:59:19,482 ] 124 root - INFO: df RECEIVED for transformation in fit_to_transformations() at data_transformation_utils.py, train_shape:(1, 20)
[ 2023-05-16 00:59:19,482 ] 77 root - INFO: fetch request for [imputer] RECEIVED in get_preprocessor_from_shelve() at general_utils.py
[ 2023-05-16 00:59:19,494 ] 85 root - INFO: object [ColumnTransformer(transformers=[('numeric_imputer',
                                 SimpleImputer(strategy='median'),
                                 ['Delivery_person_Age',
                                  'Delivery_person_Ratings',
                                  'Restaurant_latitude', 'Restaurant_longitude',
                                  'Delivery_location_latitude',
                                  'Delivery_location_longitude', 'Time_Orderd',
                                  'Time_Order_picked', 'Vehicle_condition',
                                  'multiple_deliveries', 'Order_Day',
                                  'Order_Month', 'Geo_Distance']),
                                ('categoric_imputation',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Delivery_person_ID', 'Weather_conditions',
                                  'Road_traffic_density', 'Type_of_order',
                                  'Type_of_vehicle', 'Festival', 'City'])])] of type [<class 'sklearn.compose._column_transformer.ColumnTransformer'>] retrieved and RETURNED from preprosessor shelve
[ 2023-05-16 00:59:19,499 ] 138 root - INFO: imputation completed at data_transformation_utils.py, train_shape:(1, 20)
 number of train columns with null values [0]
[ 2023-05-16 00:59:19,499 ] 77 root - INFO: fetch request for [encoder_Delivery_person_ID] RECEIVED in get_preprocessor_from_shelve() at general_utils.py
[ 2023-05-16 00:59:19,505 ] 85 root - INFO: object [LabelEncoder()] of type [<class 'sklearn.preprocessing._label.LabelEncoder'>] retrieved and RETURNED from preprosessor shelve
[ 2023-05-16 00:59:19,506 ] 77 root - INFO: fetch request for [encoder_Road_traffic_density] RECEIVED in get_preprocessor_from_shelve() at general_utils.py
[ 2023-05-16 00:59:19,508 ] 85 root - INFO: object [LabelEncoder()] of type [<class 'sklearn.preprocessing._label.LabelEncoder'>] retrieved and RETURNED from preprosessor shelve
[ 2023-05-16 00:59:19,508 ] 77 root - INFO: fetch request for [encoder_Type_of_vehicle] RECEIVED in get_preprocessor_from_shelve() at general_utils.py
[ 2023-05-16 00:59:19,510 ] 85 root - INFO: object [LabelEncoder()] of type [<class 'sklearn.preprocessing._label.LabelEncoder'>] retrieved and RETURNED from preprosessor shelve
[ 2023-05-16 00:59:19,510 ] 77 root - INFO: fetch request for [encoder_City] RECEIVED in get_preprocessor_from_shelve() at general_utils.py
[ 2023-05-16 00:59:19,512 ] 85 root - INFO: object [LabelEncoder()] of type [<class 'sklearn.preprocessing._label.LabelEncoder'>] retrieved and RETURNED from preprosessor shelve
[ 2023-05-16 00:59:19,512 ] 166 root - CRITICAL: Exception logged from file [c:\users\u1143589\learning\ineuron\ml\food_delivery_time\src\utils\data_transformation_utils.py] line no. [148] with message [y contains previously unseen labels: 'Metropolitan']
[ 2023-05-16 00:59:19,512 ] 47 root - CRITICAL: Exception logged from file [c:\users\u1143589\learning\ineuron\ml\food_delivery_time\src\components\prediction.py] line no. [38] with message [Exception logged from file [c:\users\u1143589\learning\ineuron\ml\food_delivery_time\src\utils\data_transformation_utils.py] line no. [148] with message [y contains previously unseen labels: 'Metropolitan']]
